#!/usr/bin/env python3
"""Discover YouTube videos into a deduplicated ingestion URL list."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any

from transcript_pipeline import (
    ROOT,
    canonical_youtube_url,
    find_binary,
    load_records,
    run,
    youtube_video_id,
)


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")[:60] or "queue"


def discover(
    yt_dlp: str,
    target: str,
    *,
    limit: int,
    cookies_from_browser: str | None,
) -> list[dict[str, Any]]:
    command = [
        yt_dlp,
        "--dump-single-json",
        "--flat-playlist",
        "--skip-download",
        "--no-warnings",
        "--playlist-end",
        str(limit),
    ]
    if cookies_from_browser:
        command.extend(["--cookies-from-browser", cookies_from_browser])
    command.append(target)
    result = run(command, capture=True, timeout=300)
    payload = json.loads(result.stdout)
    return list(payload.get("entries") or [payload])


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Find healthcare videos or expand a playlist/channel into a queue."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--query", help="YouTube search query.")
    source.add_argument("--url", help="Playlist, channel, or video URL.")
    parser.add_argument("--limit", type=int, default=25)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--channel", action="append", default=[])
    parser.add_argument("--min-duration", type=int, default=30)
    parser.add_argument("--max-duration", type=int, default=7200)
    parser.add_argument("--include-published", action="store_true")
    parser.add_argument("--cookies-from-browser")
    parser.add_argument("--yt-dlp", default=os.environ.get("YT_DLP_BINARY"))
    args = parser.parse_args()

    yt_dlp = find_binary("yt-dlp", args.yt_dlp)
    target = f"ytsearch{args.limit}:{args.query}" if args.query else str(args.url)
    entries = discover(
        yt_dlp,
        target,
        limit=args.limit,
        cookies_from_browser=args.cookies_from_browser,
    )
    published = {str(record.get("videoId")) for record in load_records()}
    allowed_channels = {value.casefold() for value in args.channel}

    candidates: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for entry in entries:
        video_id = str(entry.get("id") or "")
        if not youtube_video_id(video_id):
            webpage_url = str(entry.get("webpage_url") or entry.get("url") or "")
            video_id = youtube_video_id(webpage_url) or ""
        if not video_id or video_id in seen:
            continue
        duration = int(entry.get("duration") or 0)
        if duration and not (args.min_duration <= duration <= args.max_duration):
            continue
        channel = str(entry.get("channel") or entry.get("uploader") or "")
        if allowed_channels and channel.casefold() not in allowed_channels:
            continue
        if video_id in published and not args.include_published:
            continue
        seen.add(video_id)
        candidates.append(
            (
                canonical_youtube_url(video_id),
                str(entry.get("title") or video_id),
                channel,
            )
        )

    default_name = slugify(args.query or Path(str(args.url)).name or "queue")
    output = args.output or ROOT / "queues" / f"{default_name}.txt"
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/discover.py",
        *[
            f"{url}  # {title}" + (f" — {channel}" if channel else "")
            for url, title, channel in candidates
        ],
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(candidates)} video URL(s) to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
